cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

dark_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView
from accounts import views as account_views
from main import views as main_views
from vendorpanel import views as vendor_views
from main import views as product_views

urlpatterns = [
    path('alibaba/', admin.site.urls),
    path('support/', include('support.urls')),
    # path('vendor/', include('vendor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^signin/$', account_views.LoginView.as_view(), name='signin'),
    url(r'^signin/gpgauth/$', account_views.gpgauth, name='gpgauth'),
    url(r'^signin/gpgverify/$', account_views.gpgverify, name='gpgverify'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/signin')),
    url(r'^profile/usetfalogin', account_views.usetfalogin, name='usetfalogin'),
    #vendor Urls
    url(r'^vendor/addproduct', vendor_views.addProduct, name='user_vendor_addproduct'),
    url(r'^vendor/saveProduct', vendor_views.saveProduct, name='user_vendor_saveProduct'),
    url(r'^vendor/deleteProduct/(?P<product_id>\d+)/$', vendor_views.deleteProduct, name='user_vendor_deleteProduct'),
    url(r'^vendor/editProduct/(?P<product_id>\d+)/$', vendor_views.editProduct, name='user_vendor_editProduct'),
    url(r'^vendor/updateProduct/$', vendor_views.updateProduct, name='user_vendor_updateProduct'),
    url(r'^vendor/listProducts', vendor_views.listProducts, name='user_vendor_listProducts'),
    url(r'^vendorProfile/(?P<id>\d+)/', account_views.vendorProfile, name='vendorProfile'),
    url(r'^vendorPublicProfile/(?P<id>\d+)/', account_views.vendorPublicProfile, name='vendorPublicProfile'),
    url(r'^vendor/newOrders/$', vendor_views.VendorNewOrderListView.as_view(), name='vendor_list_new_order'),
    url(r'^vendor/newOrders/(?P<order_id>\d+)/$', vendor_views.VendorNewOrderDetailView.as_view(), name='vendor_detail_new_order'),
    url(r'^vendor/shipOrders/$', vendor_views.VendorShippedOrderListView.as_view(), name='vendor_list_ship_order'),
    url(r'^vendor/shipOrders/(?P<order_id>\d+)/$', vendor_views.VendorShippedOrderDetailView.as_view(), name='vendor_detail_ship_order'),
    url(r'^vendor/completeOrders/$', vendor_views.VendorCompleteOrderListView.as_view(), name='vendor_list_complete_order'),
    url(r'^vendor/completeOrders/(?P<order_id>\d+)/$', vendor_views.VendorCompleteOrderDetailView.as_view(), name='vendor_detail_complete_order'),
    url(r'^vendor/cancelOrders/$', vendor_views.VendorCancelOrderListView.as_view(), name='vendor_list_cancel_order'),
    url(r'^vendor/cancelOrders/(?P<order_id>\d+)/$', vendor_views.VendorCancelOrderDetailView.as_view(), name='vendor_detail_cancel_order'),
    url(r'^vendor/disputeOrders/$', vendor_views.VendorDisputeOrderListView.as_view(), name='vendor_list_dispute_order'),
    url(r'^vendor/disputeOrders/(?P<order_id>\d+)/$', vendor_views.VendorDisputeOrderDetailView.as_view(), name='vendor_detail_dispute_order'),
    #url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.VendorAcceptOrderView.as_view(), name='vendor_accept_order'),
    url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.accept_order, name='vendor_accept_order'),
    url(r'^vendor/rejectOrder/(?P<order_id>\d+)/$', vendor_views.reject_order, name='vendor_reject_order'),
    url(r'^vendor/newShippingOption/$', vendor_views.addShippingOption, name='vendor_list_new_shipping_option'),
    url(r'^vendor/saveNewShippingOption', vendor_views.saveNewShippingOption, name='user_vendor_saveNewShippingOption'),
    url(r'^vendor/listShippingOptions', vendor_views.listShippingOptions, name='user_vendor_listShippingOptions'),
    url(r'^vendor/editShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.editShippingOption, name='user_vendor_editShippingOption'),
    url(r'^vendor/updateShippingOption/$', vendor_views.updateShippingOption, name='user_vendor_updateShippingOption'),
    url(r'^vendor/deleteShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.deleteShippingOption, name='user_vendor_deleteShippingOption'),
    #seach url
    url(r'^search/$', product_views.search, name='search'),
    # path('accounts/', include('django.contrib.auth.urls')),

    url(r'^messages/$', product_views.UserMessageListView.as_view(), name='message_list'),

    #inbox url
    url(r'^inbox/$', product_views.UserInboxListView.as_view(), name='inbox_list'),
    url(r'^inbox/(?P<message_id>\d+)/delete/$', product_views.deleteMessage, name='inbox_delete_message'),
    url(r'^inbox/send/$', product_views.inbox_send, name='inbox_send'),
    url(r'^inbox/send/(?P<receiver_id>\d+)/$', product_views.inbox_send, name='inbox_send'),

    path('account/', include('accounts.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),  # Redirects url "/accounts" to "/account"
    # url(r'^accounts/', include("accounts.passwords.urls")),

    # path('accounts/', include("accounts.passwords.urls")),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls')),
    #star Rating Url
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as views
from main import views as main_views
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    #url(r'^messages/', views.UserMessageListView.as_view(), name='message_list'),

]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/(?P<product_id>\d+)/$', views.order_create, name='order_create'),
    url(r'^(?P<order_id>\d+)/(?P<product_id>\d+)/pay/$', views.pay, name='pay'),
    url(r'^waiting/(?P<order_id>\d+)/(?P<addres>[-\w]+)/(?P<cost>\d+\.\d{8})$', views.waiting, name='waiting'),
]

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.Form):
        address = forms.CharField(
            max_length=3000,
            widget=forms.Textarea())

main/views.py
from cart.forms import CartAddProductForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, ListView
from orders.models import OrderItem, Order
from django.shortcuts import render, get_object_or_404, redirect
from cryptowatch_client import Client

from .models import Category, Product, Message, BTCPrice
from django_countries import countries
from accounts.models import User, VendorTerm
from django.db.models import Q
from star_ratings.models import Rating, UserRating
from accounts.forms import LoginForm
from django.db.models import Q
from vendorpanel.models import ShippingOption

# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             msg = "Hello " + user.username + ". Welcome to OnionShop."
#             messages.success(request, msg)
#             return redirect("product_list")
#     else:
#         form = SignUpForm()
#     return render(request, 'registration/signup.html', {'form': form})
#
#
# def signin(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             msg = "Welcome back" + user.username
#             messages.success(request, msg)
#             return redirect("product_list")
#     else:
#         form = LoginForm(request)
#     return render(request, 'registration/login.html', {'form': form})
def cryptocurrencies():
    btcPrice = BTCPrice.objects.all().order_by('-id').first()
    if btcPrice == None:
        cryptoPrice={"btcusd":"",'btcgbp':"",'btceur':""}
    else:
        cryptoPrice={"btcusd":btcPrice.btcusd,'btcgbp':btcPrice.btcgbp,'btceur':btcPrice.btceur}
    return cryptoPrice

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    message = len(Message.objects.filter(check=False))
    #message = len(Message.objects.all())
    form = LoginForm
    if category_slug:
        print(category_slug)
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    #cryptocurrenies Data
    cryptoData=cryptocurrencies()

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'cryptoData': cryptoData,
        'countries': countries,
        'form': form,
        'new_message': message,
    }
    return render(request, 'main/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    product_stock = cart_product_form.get_product_stock(id)
    categories = Category.objects.all()
    cryptoData = cryptocurrencies()
    message = len(Message.objects.filter(check=False))

    productVendor = Product.objects.values('productOwnerID', 'country').get(id=id)
    country = countries.name(productVendor.get('country'))
    productVendor = productVendor.get('productOwnerID')

    vendor = User.objects.values('id', 'username').filter(id=productVendor, is_vendor=True)
    ratings = Rating.objects.filter(object_id=id)
    term_conditions = VendorTerm.objects.filter(userId=productVendor)
    if ratings:
        ratingsObject = UserRating.objects.filter(rating=ratings.first().id).first()
    else:
        ratingsObject = None
    if request.user.is_authenticated and product.country==request.user.country:
        shipping_options = ShippingOption.objects.filter(
                           shipping_area='domestic',
                           vendor=product.productOwnerID)
    else:
        shipping_options = ShippingOption.objects.filter(
                           shipping_area='international',
                           vendor=product.productOwnerID)

    context = {
        'product': product,
        'categories': categories,
        'cart_product_form': cart_product_form,
        'product_stock': product_stock,
        'vendor': vendor[0],
        'country': country,
        'ratingsObject': ratingsObject,
        'cryptoData': cryptoData,
        'new_message': message,
        'term_conditions': term_conditions[0],
        'shipping_options': shipping_options
    }
    return render(request, 'main/product/detail.html', context)


def search(request):
    if request.method == 'GET':
        message = len(Message.objects.filter(check=False))
        price = 0
        if request.GET.get('price'):
            price = int(request.GET.get('price'))

        country = request.GET.get('country', None)
        category = request.GET.get('category', None)
        categoryID = Category.objects.filter(name=category)
        products = {}

        if price > 0 and category is '' and country is '':
            products = Product.objects.filter(Q(price__gte=price))
        elif category and price is 0 and country is '':
            print("===================================")
            products = Product.objects.filter(category__in=categoryID)
        elif country and price is 0 and category is '':
            products = Product.objects.filter(country=country)
        elif price > 0 and category and country is '':
            products = Product.objects.filter(Q(price__gte=price), category__in=categoryID)
        elif country and price > 0 and category is '':
            products = Product.objects.filter(Q(price__gte=price), country=country)
        elif country and category and price is 0:
            products = Product.objects.filter(country=country, category__in=categoryID)
        elif price > 0 and category and country:
            products = Product.objects.filter(Q(price__gte=price), category__in=categoryID, country=country)
        elif price is 0 and category is '' and country is '':
            products = Product.objects.all

        categories = Category.objects.all()
        # cryptocurrenies Data
        cryptoData = cryptocurrencies()

        context = {
            'category': category,
            'categories': categories,
            'products': products,
            'cryptoData': cryptoData,
            'countries': countries,
            'new_message': message

        }
    else:
        raise  Exception("405")
    return render(request, 'main/product/list.html', context)


# User Notification page
class UserMessageListView(LoginRequiredMixin, ListView):
    template_name = 'message/message_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        admin_ids = User.objects.filter(id=True)
        return Message.objects.filter(Q(sender__in=admin_ids) & Q(receiver=self.request.user)).order_by('-created_at')
               #| Message.objects.filter(sender=self.request.user)


# User Inbox page
class UserInboxListView(LoginRequiredMixin, ListView):
    template_name = 'inbox/inbox_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        return Message.objects.filter((Q(sender=self.request.user) & Q(sender_removed=False)) |
                                      (Q(receiver=self.request.user) & Q(receiver_removed=False))).order_by('-created_at')
               #| Message.objects.filter(sender=self.request.user)


# User Inbox Send page
def inbox_send(request, receiver_id = '0'):
    if request.method == 'POST':
        obj = Message()
        obj.sender_id = request.user.id
        obj.receiver_id = request.POST.get('receiver_id')
        obj.content = request.POST.get('content')
        obj.save()

        msg = "Message sent successfully"
        messages.success(request, msg)
        return redirect("inbox_send")
    else:
        users = User.objects.all
        context_object = {'users': users, 'receiver_id': int(receiver_id)}
    return render(request, 'inbox/inbox_send.html', context_object)


# User Inbox Delete Message
def deleteMessage(request, message_id=''):
    message = Message.objects.get(pk=message_id)
    message_object = Message.objects.filter(id=message_id)

    if message.sender_id == request.user.id:
        message_object.update(sender_removed=True)
    elif message.receiver_id == request.user.id:
        message_object.update(receiver_removed=True)

    msg = "Message is deleted"
    messages.success(request, msg)
    return redirect("inbox_list")

# def user_profile(request):
#     if request.user.is_authenticated:
#         context = {
#             'object': request.user,
#         }
#         return render(request, 'main/profile/user-profile.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#
#
# class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
#     form_class = UserProfileChangeForm
#
#     def get_object(self, queryset=None):
#         return self.request.user
#
#     def get_success_url(self):
#         return redirect("user_profile")
#
#
# def profile_orders(request):
#     if request.user.is_authenticated is True:
#         orders = Order.objects.filter(user=request.user)
#         context = {
#             'orders': orders,
#         }
#         return render(request, 'main/profile/order-list.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#
#
# def profile_order(request, order_id):
#     if request.user.is_authenticated is True:
#         orders = OrderItem.objects.filter(order_id=order_id, author=request.user)
#
#         context = {
#             'orders': orders,
#         }
#         return render(request, 'main/profile/order-detail.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#

main/templates/orders/order/create.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Your Shopping Cart | Checkout
{% endblock %}

{% block content %}
    <div id="sidebar" class="span3">
			<div class="" style="margin-bottom: 20px">
				<p class="side-header">Search</p>
				<ul class="side-back" style="margin-top: -16px">
					<form class="form-inline" action="{% url 'search' %}" method="get">
                      {% csrf_token %}
                      <div class="">
                          <!--<label for="category">Category :</label>-->
                        <select  name="category" class="side-search"  id="category" value="">
                            <option value="">Select Category</option>
                            {% for c in categories %}
                            <option value="{{ c.name }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
                      <div class="">
                          <!--<label for="price">Price :</label>-->
                          <input type="number" id="price" class="side-search" placeholder="Enter Price" min="0" name="price" value="" />
                      </div>
                      <div class="">
                          <!--<label for="country">Shipped From :</label>-->
                        <select  name="country" class="side-search" id="country" value="">
                            <option value="">Select Country</option>
                            {% for c in countries %}
                            <option value="{{ c.code }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
					  <div>
                      	<button type="submit" class="side-search">Search</button>
					  </div>
                    </form>
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header">category</p>
				<ul class="side-back" style="margin-top: -16px">
					<li class="side-content" ><a href="{% url 'product_list' %}" style="color: #6ec2d1">All</a></li>
            		{% for c in categories %}

              			<li class="side-content" >
                  			<a href="{{ c.get_absolute_url }}" style="color: #6ec2d1"><span class="icon-chevron-right"></span>{{ c.name }}</a>
              			</li>
            		{% endfor %}
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header"> 1 btc price</p>
				<ul class="side-back" style="margin-top: -16px">
					<!--<li class="side-content" >
                  		<i class="fa fa-btc"></i>BTC  1
                  	</li>-->
                  	<li class="side-content">
						<a style="color: #6ec2d1">USD  {{ cryptoData.btcusd }}</a>
                  	</li>
					<li class="side-content">
                      	<a style="color: #6ec2d1">GBP  {{ cryptoData.btcgbp }}</a>
                  	</li>
                    <li class="side-content">
                      	<a style="color: #6ec2d1">EUR  {{ cryptoData.btceur }}</a>
                  	</li>
				</ul>
			</div>

		</div>
    <div class="span9">
    	<ul class="breadcrumb">
            <li class="cate-name">Checkout</li>
            <!--<span class="badge pull-right" style="background-color: #f89406; font-size: 18px">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff; ">
                            {{ totail_items }} item{{ totail_items|pluralize }}, $ {{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>-->
        </ul>
        <div class="well well-small" style="background-color: #0d0d0d; border: none">
            <div class="row-fluid">
            {% if request.user.is_authenticated %}

            {% else %}
                <div style="margin-top:20px;margin-bottom:20px">
                    <h6>You do not have an account, you must create an account,or <a style="text-decoration:underline" href="{% url 'signin' %}">Sign-in</a> to order</h6>
                </div>
            {% endif %}
                <div class="span6">
                    <form action="." method="post" class="m-l-sm">
                        {% csrf_token %}

                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                 {% comment %}{{ field.label_tag }}{% endcomment %}
                                {% comment %}<div  style="background: url({% static '/assets/img/title-long.jpg' %}); height: 30px">{% endcomment %}
                                    <label for="id_{{field.label}}" style="background: url({% static '/assets/img/title-long.jpg' %}) no-repeat; height: 30px;color: #6ec2d1; padding: 5px 0 0 35px">
                                        {{ field.label }}
                                    </label>
                                {% comment %}</div>{% endcomment %}
                                  {% if form.is_bound %}
                                    {% if field.errors %}
                                      {% render_field field class="form-control is-invalid" %}
                                      {% for error in field.errors %}
                                        <div class="invalid-feedback">
                                          {{ error }}
                                        </div>
                                      {% endfor %}
                                    {% else %}
                                      {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                  {% else %}
                                    {% render_field field class="form-control" style="background: #141414;margin-top: -10px; width: 96.5%; border: none;color"%}
                                  {% endif %}
                                </div>
                              {% endfor %}

                        <br>
                        {% if request.user.is_authenticated %}
                            <input type="submit" class="btn btn-primary" value="Submit Order">
                        {% else %}
                            <input type="submit" class="btn btn-primary" value="Signup">
                        {% endif %}

                    </form>
                </div>
                <div class="span6 title-back m-l-sm">
                    <div style="background: url({% static 'assets/img/title-long.jpg' %}); height: 30px; width: 100%">
                        <label style="color: #6ec2d1; padding: 5px 0 0 35px"> Your Order</label>
                    </div>
                    <ul class="list-group">
                    {% for item in cart %}
                        {% if product_id == item.product.id %}
                        <li class="list-group-item" style="list-style: none; background: #141414">
                            <div class="span6">
                                <p style="color: #666">{{ item.quantity }}  x  {{ item.product.name }}</p>
                            </div>

                        <span class="text-warn">      $ {{ item.total_price }}</span>
                        </li>
                        {% comment %}{% endif %}
                    {% endfor %}{% endcomment %}

                        <li style="list-style: none; background: #141414;border-top: 1px solid #3b3b3b">
                            <div class="span6">
                                <h3 style="color: #666">Total Cost:</h3>
                            </div>
                            <div class="span6">
                                <h3 class="text-warn"> $ {{ item.total_price }}</h3>
                            </div>
                        </li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/orders/order/created.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 12%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/orders/order/pay.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
<div id="sidebar" class="span3">
			<div class="" style="margin-bottom: 20px">
				<p class="side-header">Search</p>
				<ul class="side-back" style="margin-top: -16px">
					<form class="form-inline" action="{% url 'search' %}" method="get">
                      {% csrf_token %}
                      <div class="">
                          <!--<label for="category">Category :</label>-->
                        <select  name="category" class="side-search"  id="category" value="">
                            <option value="">Select Category</option>
                            {% for c in categories %}
                            <option value="{{ c.name }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
                      <div class="">
                          <!--<label for="price">Price :</label>-->
                          <input type="number" id="price" class="side-search" placeholder="Enter Price" min="0" name="price" value="" />
                      </div>
                      <div class="">
                          <!--<label for="country">Shipped From :</label>-->
                        <select  name="country" class="side-search" id="country" value="">
                            <option value="">Select Country</option>
                            {% for c in countries %}
                            <option value="{{ c.code }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
					  <div>
                      	<button type="submit" class="side-search">Search</button>
					  </div>
                    </form>
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header">category</p>
				<ul class="side-back" style="margin-top: -16px">
					<li class="side-content" ><a href="{% url 'product_list' %}" style="color: #6ec2d1">All</a></li>
            		{% for c in categories %}

              			<li class="side-content" >
                  			<a href="{{ c.get_absolute_url }}" style="color: #6ec2d1"><span class="icon-chevron-right"></span>{{ c.name }}</a>
              			</li>
            		{% endfor %}
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header"> 1 btc price</p>
				<ul class="side-back" style="margin-top: -16px">
					<!--<li class="side-content" >
                  		<i class="fa fa-btc"></i>BTC  1
                  	</li>-->
                  	<li class="side-content">
						<a style="color: #6ec2d1">USD  {{ cryptoData.btcusd }}</a>
                  	</li>
					<li class="side-content">
                      	<a style="color: #6ec2d1">GBP  {{ cryptoData.btcgbp }}</a>
                  	</li>
                    <li class="side-content">
                      	<a style="color: #6ec2d1">EUR  {{ cryptoData.btceur }}</a>
                  	</li>
				</ul>
			</div>

		</div>
<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="container">
                <div class="row" >
            <ul> 
                <li style="color: #666">Bitcoin Addres: {{addres}}</li>
                <li style="color: #666">Cash Amount: $ {{total_price}}</li>
                <li style="color: #666">Bitcoin Amount: {{btc_price}}</li>
                <li style="color: #666">Current bitcoin course: $ {{btc_course}}</li>
                <li style="color: #666">Once you have paid click the link bellow and we will verify that you completed the transaction</li>
                <li style="color: #666">You have to confirm your payment within 24 hours. If not, your shipping cart will be deleted automatically.</li>
                <li style="color: #666">After vendor accept your cart, if you don't receive products within 10 days, you can dispute your cart.</li>
                <li style="list-style: none"><a class="btn btn-success btn-sm m-t-md" style = "" href = "{% url 'orders:waiting' order_id=order_id addres=addres cost=btc_price %}">Confirm Payment</a></li>
            </ul>
        </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}