cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

dark_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView
from accounts import views as account_views
from main import views as main_views
from vendorpanel import views as vendor_views
from main import views as product_views

urlpatterns = [
    path('alibaba/', admin.site.urls),
    path('support/', include('support.urls')),
    # path('vendor/', include('vendor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^signin/$', account_views.LoginView.as_view(), name='signin'),
    url(r'^signin/gpgauth/$', account_views.gpgauth, name='gpgauth'),
    url(r'^signin/gpgverify/$', account_views.gpgverify, name='gpgverify'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/signin')),
    url(r'^profile/usetfalogin', account_views.usetfalogin, name='usetfalogin'),
    #vendor Urls
    url(r'^vendor/addproduct', vendor_views.addProduct, name='user_vendor_addproduct'),
    url(r'^vendor/saveProduct', vendor_views.saveProduct, name='user_vendor_saveProduct'),
    url(r'^vendor/deleteProduct/(?P<product_id>\d+)/$', vendor_views.deleteProduct, name='user_vendor_deleteProduct'),
    url(r'^vendor/editProduct/(?P<product_id>\d+)/$', vendor_views.editProduct, name='user_vendor_editProduct'),
    url(r'^vendor/updateProduct/$', vendor_views.updateProduct, name='user_vendor_updateProduct'),
    url(r'^vendor/listProducts', vendor_views.listProducts, name='user_vendor_listProducts'),
    url(r'^vendorProfile/(?P<id>\d+)/', account_views.vendorProfile, name='vendorProfile'),
    url(r'^vendorPublicProfile/(?P<id>\d+)/', account_views.vendorPublicProfile, name='vendorPublicProfile'),
    url(r'^vendor/newOrders/$', vendor_views.VendorNewOrderListView.as_view(), name='vendor_list_new_order'),
    url(r'^vendor/newOrders/(?P<order_id>\d+)/$', vendor_views.VendorNewOrderDetailView.as_view(), name='vendor_detail_new_order'),
    url(r'^vendor/shipOrders/$', vendor_views.VendorShippedOrderListView.as_view(), name='vendor_list_ship_order'),
    url(r'^vendor/shipOrders/(?P<order_id>\d+)/$', vendor_views.VendorShippedOrderDetailView.as_view(), name='vendor_detail_ship_order'),
    url(r'^vendor/completeOrders/$', vendor_views.VendorCompleteOrderListView.as_view(), name='vendor_list_complete_order'),
    url(r'^vendor/completeOrders/(?P<order_id>\d+)/$', vendor_views.VendorCompleteOrderDetailView.as_view(), name='vendor_detail_complete_order'),
    url(r'^vendor/cancelOrders/$', vendor_views.VendorCancelOrderListView.as_view(), name='vendor_list_cancel_order'),
    url(r'^vendor/cancelOrders/(?P<order_id>\d+)/$', vendor_views.VendorCancelOrderDetailView.as_view(), name='vendor_detail_cancel_order'),
    url(r'^vendor/disputeOrders/$', vendor_views.VendorDisputeOrderListView.as_view(), name='vendor_list_dispute_order'),
    url(r'^vendor/disputeOrders/(?P<order_id>\d+)/$', vendor_views.VendorDisputeOrderDetailView.as_view(), name='vendor_detail_dispute_order'),
    #url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.VendorAcceptOrderView.as_view(), name='vendor_accept_order'),
    url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.accept_order, name='vendor_accept_order'),
    url(r'^vendor/rejectOrder/(?P<order_id>\d+)/$', vendor_views.reject_order, name='vendor_reject_order'),
    url(r'^vendor/newShippingOption/$', vendor_views.addShippingOption, name='vendor_list_new_shipping_option'),
    url(r'^vendor/saveNewShippingOption', vendor_views.saveNewShippingOption, name='user_vendor_saveNewShippingOption'),
    url(r'^vendor/listShippingOptions', vendor_views.listShippingOptions, name='user_vendor_listShippingOptions'),
    url(r'^vendor/editShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.editShippingOption, name='user_vendor_editShippingOption'),
    url(r'^vendor/updateShippingOption/$', vendor_views.updateShippingOption, name='user_vendor_updateShippingOption'),
    url(r'^vendor/deleteShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.deleteShippingOption, name='user_vendor_deleteShippingOption'),
    #seach url
    url(r'^search/$', product_views.search, name='search'),
    # path('accounts/', include('django.contrib.auth.urls')),

    url(r'^messages/$', product_views.UserMessageListView.as_view(), name='message_list'),

    #inbox url
    url(r'^inbox/$', product_views.UserInboxListView.as_view(), name='inbox_list'),
    url(r'^inbox/(?P<message_id>\d+)/delete/$', product_views.deleteMessage, name='inbox_delete_message'),
    url(r'^inbox/send/$', product_views.inbox_send, name='inbox_send'),
    url(r'^inbox/send/(?P<receiver_id>\d+)/$', product_views.inbox_send, name='inbox_send'),

    path('account/', include('accounts.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),  # Redirects url "/accounts" to "/account"
    # url(r'^accounts/', include("accounts.passwords.urls")),

    # path('accounts/', include("accounts.passwords.urls")),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls')),
    #star Rating Url
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/(?P<product_id>\d+)/$', views.order_create, name='order_create'),
    url(r'^(?P<order_id>\d+)/(?P<product_id>\d+)/pay/$', views.pay, name='pay'),
    url(r'^waiting/(?P<order_id>\d+)/(?P<addres>[-\w]+)/(?P<cost>\d+\.\d{8})$', views.waiting, name='waiting'),
]

main/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from accounts.models import User
from django.core.validators import MinValueValidator


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='message_sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='message_receiver', on_delete=models.CASCADE)
    content = models.TextField(default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    check = models.BooleanField(default=False)
    sender_removed = models.BooleanField(default=False)
    receiver_removed = models.BooleanField(default=False)

    def get_sender(self):
        return self.sender

    def get_receiver(self):
        return self.receiver


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1.0)])
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    country = CountryField(null=True)
    productOwnerID = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Owner ID',
                                       editable=False, default=1)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])


class BTCPrice(models.Model):
    btcgbp = models.FloatField()
    btcusd = models.FloatField()
    btceur = models.FloatField()

orders/models.py
from django.db import models
from main.models import Product
from django.contrib.auth import get_user_model

User = get_user_model()


class Pay(models.Model):
    timestamp = models.DateTimeField(blank=True, null=True)
    address = models.CharField(max_length=300)
    btc_course = models.DecimalField(decimal_places=8, max_digits=20, default=0)
    amount_expected = models.DecimalField(decimal_places=8, max_digits=20)
    amount_received = models.DecimalField(decimal_places=8, max_digits=20)
    vendor_amount = models.DecimalField(decimal_places=8, max_digits=20, default=0)
    fee_amount = models.DecimalField(decimal_places=8, max_digits=20, default=0)
    status = models.CharField(max_length=5, default='0')
    author = models.CharField(max_length=100, default='none')

    def __str__(self):
        return self.address


class Order(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    address = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    payment = models.ForeignKey(Pay, related_name='payment', blank=True, null=True, on_delete=models.CASCADE)
    #paid = models.BooleanField(default=False)
    paid = models.CharField(max_length=5, default="0")    

    class Meta:
        ordering = ('-created_at', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.Form):
        address = forms.CharField(
            max_length=3000,
            widget=forms.Textarea())

orders/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import OrderItem,Order,Pay
from .forms import OrderCreateForm
from cart.cart import Cart
from accounts.forms import SignUpForm
from django.contrib.auth import login, authenticate
import requests
from bitcoinrpc.authproxy import AuthServiceProxy, JSONRPCException
from django.utils import timezone
from .tasks import update
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from main.models import Category, Product
from cryptowatch_client import Client

"""
rememeber to add cart.clear()
"""

def cryptocurrencies():
    client = Client(timeout=30)
    btcgbp = client.get_markets_price(exchange='gdax', pair='btcgbp')
    btcusd = client.get_markets_price(exchange='gdax', pair='btcusd')
    btceur = client.get_markets_price(exchange='gdax', pair='btceur')
    btcgbp_response = btcgbp.json()
    btcusd_response = btcusd.json()
    btceur_response = btceur.json()
    btcgbpPrice=btcgbp_response.get('result').get('price')
    btcusdPrice=btcusd_response.get('result').get('price')
    btceurPrice=btceur_response.get('result').get('price')
    cryptoPrice={"btcusd":btcusdPrice,'btcgbp':btcgbpPrice,'btceur':btceurPrice}
    return cryptoPrice

def waiting(request,order_id, addres, cost):
   #update.apply_async((order_id, addres, cost), countdown=1200)

    content = "Will send you message after confirm your transaction. Please wait some times during confirm your transaction."
    return render(request, "orders/order/waiting.html", {'content': content})


def pay(request, order_id, product_id):
    cart = Cart(request)
    btc_course = (requests.get("https://api.coindesk.com/v1/bpi/currentprice/USD.json").json())["bpi"]['USD']["rate_float"]
    total_price = cart.get_total_price(product_id)
    btc_price = round((float(cart.get_total_price(product_id))/float(btc_course)), 8)
    if total_price > 0:
        rpc_user = "NSA12012"
        rpc_password = "ZIwnhqsa"
        rpc_connection = AuthServiceProxy("http://%s:%s@213.227.140.1:8332" % (rpc_user, rpc_password))
        print("=============================")
        addres = rpc_connection.getnewaddress()
        print(addres)
        pay = Pay.objects.create(timestamp=timezone.now(), btc_course=btc_course, amount_expected=btc_price,
                                 amount_received=0, author=request.user.username, status=0, address=addres)
        pay.save()
        Order.objects.filter(id=order_id).update(payment=pay, paid="1")
        cart.clear_item(product_id)
        return render(request, 'orders/order/pay.html',
                      {'order_id': order_id, 'addres': addres, 'btc_course': btc_course, "total_price": total_price,
                       "btc_price": btc_price})

    else:
        content = "Cart Items are Zero. Please cart products."
        return render(request, "orders/order/waiting.html", {'content': content})


def order_create(request, product_id):
    cart = Cart(request)
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=product_id)
    #cart_aaa = cart.get_item(product_id)
    cryptoData = cryptocurrencies()
    if request.user.is_authenticated == True:
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                print("addrr===>> ", form['address'].value())
                order = Order.objects.create(
                    user=request.user,
                    address=form['address'].value()
                )
                print("----->>> ", order)
                #for item in cart:
                #    OrderItem.objects.create(
                #        author=request.user,
                #        order=order,
                #        product=item['product'],
                #        price=item['price'],
                #        quantity=item['quantity']
                #    )
                OrderItem.objects.create(
                    author=request.user,
                    order=order,
                    product=product,
                    price=cart.get_item_price(product_id),
                    quantity=cart.get_item_quantity(product_id)
                )

                product = Product.objects.get(id=product_id)
                stock = product.stock - cart.get_item_quantity(product_id)
                Product.objects.filter(id=product_id).update(stock=stock)
            #return HttpResponseRedirect(reverse('orders:pay', args=[order.id]))
            return HttpResponseRedirect(reverse('orders:pay', kwargs={'order_id': order.id, 'product_id': product_id}))
        else:
            form = OrderCreateForm()
        context = {
            'form': form,
            'categories': categories,
            'cryptoData': cryptoData,
            'product_id': int(product_id)
        }
        return render(request, 'orders/order/create.html', context)
    elif request.user.is_authenticated == False:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('orders:order_create')
            else:
                form = SignUpForm()
                return render(request, 'orders/order/create.html', {'form': form})
        else:
            form = SignUpForm()
            return render(request, 'orders/order/create.html', {'form': form})
        return redirect('orders:order_create')

orders/templates/order/create_old.html
{% extends 'main/base.html' %}
{% load static %}
{% load ratings %}
{% block title %}
    Your Shopping Cart - Checkout
{% endblock %}


{% block content %}
    <div id="sidebar" class="span3">
			<div class="" style="margin-bottom: 20px">
				<p class="side-header">Search</p>
				<ul class="side-back" style="margin-top: -16px">
					<form class="form-inline" action="{% url 'search' %}" method="get">
                      {% csrf_token %}
                      <div class="">
                          <!--<label for="category">Category :</label>-->
                        <select  name="category" class="side-search"  id="category" value="">
                            <option value="">Select Category</option>
                            {% for c in categories %}
                            <option value="{{ c.name }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
                      <div class="">
                          <!--<label for="price">Price :</label>-->
                          <input type="number" id="price" class="side-search" placeholder="Enter Price" min="0" name="price" value="" />
                      </div>
                      <div class="">
                          <!--<label for="country">Shipped From :</label>-->
                        <select  name="country" class="side-search" id="country" value="">
                            <option value="">Select Country</option>
                            {% for c in countries %}
                            <option value="{{ c.code }}">{{ c.name }}</option>
                            {% endfor %}
                        </select>
                      </div>
					  <div>
                      	<button type="submit" class="side-search">Search</button>
					  </div>
                    </form>
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header">category</p>
				<ul class="side-back" style="margin-top: -16px">
					<li class="side-content" ><a href="{% url 'product_list' %}" style="color: #6ec2d1">All</a></li>
            		{% for c in categories %}

              			<li class="side-content" >
                  			<a href="{{ c.get_absolute_url }}" style="color: #6ec2d1"><span class="icon-chevron-right"></span>{{ c.name }}</a>
              			</li>
            		{% endfor %}
				</ul>
			</div>

			<div class="" style="margin-bottom: 20px">
				<p class="side-header"> 1 btc price</p>
				<ul class="side-back" style="margin-top: -16px">
					<!--<li class="side-content" >
                  		<i class="fa fa-btc"></i>BTC  1
                  	</li>-->
                  	<li class="side-content">
						<a style="color: #6ec2d1">USD  {{ cryptoData.btcusd }}</a>
                  	</li>
					<li class="side-content">
                      	<a style="color: #6ec2d1">GBP  {{ cryptoData.btcgbp }}</a>
                  	</li>
                    <li class="side-content">
                      	<a style="color: #6ec2d1">EUR  {{ cryptoData.btceur }}</a>
                  	</li>
				</ul>
			</div>

		</div>
    <div class="span9">
    	<ul class="breadcrumb">
            <li class="cate-name">Your Shopping Cart</li>
            <!--<span class="badge pull-right" style="background-color: #f89406; font-size: 18px">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff; ">
                            {{ totail_items }} item{{ totail_items|pluralize }}, $ {{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>-->
        </ul>
        <div class="well well-small" style="background-color: #0d0d0d; border: none">
        {% for item in cart %}
            {% with product=item.product  %}
            <div class="row-fluid" style="margin-bottom: 10px;border-bottom: 1px solid #3b3b3b">
                <div class="span2">
			        <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'assets/img/default.png' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                    </a>
		        </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span6"><h4 class="content">Name : </h4></div>
                        <div class="span6"><h4 class="content1"> {{product.name}} </h4></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6"><h4 class="content">Unit Price : </h4></div>
                        <div class="span6"><h4 class="content1">$ {{item.price}} </h4></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6"><h4 class="content">Sum Price : </h4></div>
                        <div class="span6"><h4 class="content1">$ {{item.total_price}} </h4></div>
                    </div>
                    <!--<h4 class="content">Unit Price : $ {{item.price}} </h4>
                    <h4 class="content">Price : $ {{item.total_price}} </h4>-->
		        </div>
                <div class="span4 alignR">
                    <br>
		            <form action="{% url 'cart:cart_add' product.id %}" method="post">{% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                    </form>
                    <a href="{% url 'cart:cart_remove' product.id %}" class="new-button">Remove</a>
		        </div>
            </div>
            {% endwith %}
        {% endfor %}
             <div class="row-fluid" >
                 <div class="span4" style="float: right; margin-top: 10px">
                     <a href="{% url 'orders:order_create' %}" class="new-button">Checkout</a>
                 </div>
                 <div class="span6" style="float: right">
                    <div class="span6"><h4 class="content">Total : </h4></div>
                    <div class="span6"><h4 class="content1">$ {{ cart.get_total_price }}</h4></div>
                 </div>
                 <div class="span2"></div>
             </div>
        </div>
    </div>
{% endblock %}