cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

dark_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView
from accounts import views as account_views
from main import views as main_views
from vendorpanel import views as vendor_views
from main import views as product_views

urlpatterns = [
    path('alibaba/', admin.site.urls),
    path('support/', include('support.urls')),
    # path('vendor/', include('vendor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^signin/$', account_views.LoginView.as_view(), name='signin'),
    url(r'^signin/gpgauth/$', account_views.gpgauth, name='gpgauth'),
    url(r'^signin/gpgverify/$', account_views.gpgverify, name='gpgverify'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/signin')),
    url(r'^profile/usetfalogin', account_views.usetfalogin, name='usetfalogin'),
    #vendor Urls
    url(r'^vendor/addproduct', vendor_views.addProduct, name='user_vendor_addproduct'),
    url(r'^vendor/saveProduct', vendor_views.saveProduct, name='user_vendor_saveProduct'),
    url(r'^vendor/deleteProduct/(?P<product_id>\d+)/$', vendor_views.deleteProduct, name='user_vendor_deleteProduct'),
    url(r'^vendor/editProduct/(?P<product_id>\d+)/$', vendor_views.editProduct, name='user_vendor_editProduct'),
    url(r'^vendor/updateProduct/$', vendor_views.updateProduct, name='user_vendor_updateProduct'),
    url(r'^vendor/listProducts', vendor_views.listProducts, name='user_vendor_listProducts'),
    url(r'^vendorProfile/(?P<id>\d+)/', account_views.vendorProfile, name='vendorProfile'),
    url(r'^vendorPublicProfile/(?P<id>\d+)/', account_views.vendorPublicProfile, name='vendorPublicProfile'),
    url(r'^vendor/newOrders/$', vendor_views.VendorNewOrderListView.as_view(), name='vendor_list_new_order'),
    url(r'^vendor/newOrders/(?P<order_id>\d+)/$', vendor_views.VendorNewOrderDetailView.as_view(), name='vendor_detail_new_order'),
    url(r'^vendor/shipOrders/$', vendor_views.VendorShippedOrderListView.as_view(), name='vendor_list_ship_order'),
    url(r'^vendor/shipOrders/(?P<order_id>\d+)/$', vendor_views.VendorShippedOrderDetailView.as_view(), name='vendor_detail_ship_order'),
    url(r'^vendor/completeOrders/$', vendor_views.VendorCompleteOrderListView.as_view(), name='vendor_list_complete_order'),
    url(r'^vendor/completeOrders/(?P<order_id>\d+)/$', vendor_views.VendorCompleteOrderDetailView.as_view(), name='vendor_detail_complete_order'),
    url(r'^vendor/cancelOrders/$', vendor_views.VendorCancelOrderListView.as_view(), name='vendor_list_cancel_order'),
    url(r'^vendor/cancelOrders/(?P<order_id>\d+)/$', vendor_views.VendorCancelOrderDetailView.as_view(), name='vendor_detail_cancel_order'),
    url(r'^vendor/disputeOrders/$', vendor_views.VendorDisputeOrderListView.as_view(), name='vendor_list_dispute_order'),
    url(r'^vendor/disputeOrders/(?P<order_id>\d+)/$', vendor_views.VendorDisputeOrderDetailView.as_view(), name='vendor_detail_dispute_order'),
    #url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.VendorAcceptOrderView.as_view(), name='vendor_accept_order'),
    url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.accept_order, name='vendor_accept_order'),
    url(r'^vendor/rejectOrder/(?P<order_id>\d+)/$', vendor_views.reject_order, name='vendor_reject_order'),
    url(r'^vendor/newShippingOption/$', vendor_views.addShippingOption, name='vendor_list_new_shipping_option'),
    url(r'^vendor/saveNewShippingOption', vendor_views.saveNewShippingOption, name='user_vendor_saveNewShippingOption'),
    url(r'^vendor/listShippingOptions', vendor_views.listShippingOptions, name='user_vendor_listShippingOptions'),
    url(r'^vendor/editShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.editShippingOption, name='user_vendor_editShippingOption'),
    url(r'^vendor/updateShippingOption/$', vendor_views.updateShippingOption, name='user_vendor_updateShippingOption'),
    url(r'^vendor/deleteShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.deleteShippingOption, name='user_vendor_deleteShippingOption'),
    #seach url
    url(r'^search/$', product_views.search, name='search'),
    # path('accounts/', include('django.contrib.auth.urls')),

    url(r'^messages/$', product_views.UserMessageListView.as_view(), name='message_list'),

    #inbox url
    url(r'^inbox/$', product_views.UserInboxListView.as_view(), name='inbox_list'),
    url(r'^inbox/(?P<message_id>\d+)/delete/$', product_views.deleteMessage, name='inbox_delete_message'),
    url(r'^inbox/send/$', product_views.inbox_send, name='inbox_send'),
    url(r'^inbox/send/(?P<receiver_id>\d+)/$', product_views.inbox_send, name='inbox_send'),

    path('account/', include('accounts.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),  # Redirects url "/accounts" to "/account"
    # url(r'^accounts/', include("accounts.passwords.urls")),

    # path('accounts/', include("accounts.passwords.urls")),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls')),
    #star Rating Url
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from accounts.models import User
from django.core.validators import MinValueValidator


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='message_sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='message_receiver', on_delete=models.CASCADE)
    content = models.TextField(default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    check = models.BooleanField(default=False)
    sender_removed = models.BooleanField(default=False)
    receiver_removed = models.BooleanField(default=False)

    def get_sender(self):
        return self.sender

    def get_receiver(self):
        return self.receiver


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1.0)])
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    country = CountryField(null=True)
    productOwnerID = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Owner ID',
                                       editable=False, default=1)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])


class BTCPrice(models.Model):
    btcgbp = models.FloatField()
    btcusd = models.FloatField()
    btceur = models.FloatField()

templates/base_vendor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/vendor/font-awesome/css/all.css' %}">
    {% block extra_head %}

    {% endblock %}

</head>
<body>
{#Django messages#}
{% if messages %}
	{% for message in messages %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<div class="container alert alert-success messages mt-5">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
			<div class="container alert alert-info messages mt-5">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
			<div class="container alert alert-warning messages mt-5">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
			<div class="container alert alert-danger messages mt-5">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>
		{% endif %}
	{% endfor %}
{% endif %}

<div class="row">
  <div class="col-md-2">
    <nav class="navbar bg-dark justify-content-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">My Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_vendor_listProducts' %}">My Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_vendor_addproduct' %}">Add new item</a>
        </li>
      </ul>
    </nav>
  </div>

  <div class="col-md-10">
    {% block content %}

    {% endblock %}
</div>
</div>


<!--&lt;!&ndash;Main.js&ndash;&gt;-->
<!--<script type="text/javascript" src="{% static 'main/js/main.js' %}" ></script>-->

<!--&lt;!&ndash;TinyMCE.js&ndash;&gt;-->
<!--<script src="{% static 'main/js/tinymce.min.js' %}"></script>-->
<!--<script type="text/javascript" src="{% static 'main/js/tinymce-custom.js' %}" ></script>-->

</body>
</html>

templates/listProducts.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load ratings %}
{% load auth_extras %}
{% block title %}
    Vendor Panel
{% endblock %}
{% block content %}
<div id="sidebar" class="span3">
    <div class="box text-center " style="background: #141414">
            <div class="p-a-md">
				    	<p><img src="{% static '/main/img/icons/profile_user.png' %}" class="img-circle w-lg"></p>
				    	<p class="text-lg text-white block">{{ user.username }}</p>
				    	<p class="text-md text-accent">{{ user.level }}</p>
                        {% comment %}<div class="profile-userbuttons">
                            <button type="button" class="btn btn-success btn-sm">Follow</button>
                            <button type="button" class="btn btn-danger btn-sm">Message</button>
                        </div>{% endcomment %}
            </div>
            <div class="row b-t ">
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
					    <a href="{% url 'user_profile' %}">
                                    <i class="fa fa-home"></i>
                                    Overview </a>
                </div>
                {% if request.user|is_vendor %}
                <div class="col-xs-4 m-a-sm text-warn" >
                                <a href="{% url 'user_vendor_listProducts' %}">
                                    <i class="fa fa-user"></i>
                                    Vendor Panel </a>
                </div>
                {% else %}
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/settings/' %} text-warn {% else %} text-side {% endif %}">
                                <a href="{% url 'user_favorites' %}">
                                    <i class="fa fa-thumbs-up"></i>
                                    My Favorites</a>
                </div>
                {% endif %}
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
                                <a href="{% url 'user_order_list' %}">
                                    <i class="fa fa-shopping-cart"></i>
                                    My Orders </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="{% url 'user_ratings' %}">
                                    <i class="fa fa-tasks"></i>
                                    My Ratings </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-question"></i>
                                    Help </a>
                </div>
            </div>
        </div>
    <div class="" style="margin-bottom: 20px">
        <p class="side-header"> My Sales</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="{% url 'user_vendor_listProducts' %}" style="color: #6ec2d1">My Products</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_new_order' %}" style="color: #6ec2d1">New Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_ship_order' %}" style="color: #6ec2d1">Shipped Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_complete_order' %}" style="color: #6ec2d1">Completed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_cancel_order' %}" style="color: #6ec2d1">Canceled Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_dispute_order' %}" style="color: #6ec2d1">Disputed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'user_vendor_listShippingOptions' %}" style="color: #6ec2d1">Shipping Options</a>
            </li>
        </ul>
    </div>
    {% comment %}<div class="" style="margin-bottom: 20px">
        <p class="side-header"> Products</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="" style="color: #6ec2d1">Add Products</a>
            </li>
        </ul>
    </div>{% endcomment %}

</div>

<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="box" style="background: #141414; color: #666">
                <div class="box-header">
                    <h2 style="color: #6ec2d1">My Products
                        <a href="{% url 'user_vendor_addproduct' %}" ><span class="fa fa-plus text-warn m-b-md pull-right" style="font-size: 18px;">Add</span></a>
                    </h2>
                </div>
                <div class="box-divider m-0"></div>
                <table id="example" class="table box-body" style="width:100%">
                    <thead>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Stock</th>
                        <th>price</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                    {% for product in products%}
                        <tr class="b-t">
                            <td align="center">{{ product.category }}</td>
                            <td align="center">{{ product.name }}</td>
                            <td align="center">{{ product.description }}</td>
                            <td class="text-primary" align="center">{{ product.stock }}</td>
                            <td class="text-warn" align="center">$ {{ product.price }}</td>
                            <td align="center">
                                <a href="{% url 'user_vendor_editProduct' product_id=product.id %}" class="text-success">Update</a>
                                <a href="{% url 'user_vendor_deleteProduct' product_id=product.id %}" class="text-danger">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/myproducts.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load ratings %}
{% load auth_extras %}
{% block title %}
    Vendor Panel
{% endblock %}
{% block content %}
<div id="sidebar" class="span3">
    <div class="box text-center " style="background: #141414">
            <div class="p-a-md">
				    	<p><img src="{% static '/main/img/icons/profile_user.png' %}" class="img-circle w-lg"></p>
				    	<p class="text-lg text-white block">{{ user.username }}</p>
				    	<p class="text-md text-accent">{{ user.level }}</p>
                        {% comment %}<div class="profile-userbuttons">
                            <button type="button" class="btn btn-success btn-sm">Follow</button>
                            <button type="button" class="btn btn-danger btn-sm">Message</button>
                        </div>{% endcomment %}
            </div>
            <div class="row b-t ">
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
					    <a href="{% url 'user_profile' %}">
                                    <i class="fa fa-home"></i>
                                    Overview </a>
                </div>
                {% if request.user|is_vendor %}
                <div class="col-xs-4 m-a-sm text-warn" >
                                <a href="{% url 'user_vendor_listProducts' %}">
                                    <i class="fa fa-user"></i>
                                    Vendor Panel </a>
                </div>
                {% else %}
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/settings/' %} text-warn {% else %} text-side {% endif %}">
                                <a href="{% url 'user_favorites' %}">
                                    <i class="fa fa-thumbs-up"></i>
                                    My Favorites</a>
                </div>
                {% endif %}
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
                                <a href="{% url 'user_order_list' %}">
                                    <i class="fa fa-shopping-cart"></i>
                                    My Orders </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="{% url 'user_ratings' %}">
                                    <i class="fa fa-tasks"></i>
                                    My Ratings </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-question"></i>
                                    Help </a>
                </div>
            </div>
        </div>
    <div class="" style="margin-bottom: 20px">
        <p class="side-header"> My Sales</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="{% url 'user_vendor_listProducts' %}" style="color: #6ec2d1">My Products</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_new_order' %}" style="color: #6ec2d1">New Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_ship_order' %}" style="color: #6ec2d1">Shipped Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_complete_order' %}" style="color: #6ec2d1">Completed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_cancel_order' %}" style="color: #6ec2d1">Canceled Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_dispute_order' %}" style="color: #6ec2d1">Disputed Orders</a>
            </li>            

        </ul>
    </div>
    {% comment %}<div class="" style="margin-bottom: 20px">
        <p class="side-header"> Products</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="" style="color: #6ec2d1">Add Products</a>
            </li>
        </ul>
    </div>{% endcomment %}

</div>

<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="box" style="background: #141414; color: #666">
                <div class="box-header">
                    <h2 style="color: #6ec2d1">Add Products
                        {% comment %}<a href="{% url '' %}" ><span class="fa fa-plus text-warn m-b-md pull-right" style="font-size: 18px;">Add</span></a>{% endcomment %}
                    </h2>
                </div>
                <div class="box-divider m-0"></div>
                <div class="box-body">
                    <form action="{% url 'user_vendor_saveProduct'%}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group">
                            <label >Category:</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label >Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label >Slug:</label>
                            {{ form.slug }}
                        </div>
                        <div class="form-group">
                            <label >Description:</label>
                            {{ form.description }}
                        </div>

                        <div class="form-group">
                            <label >Price:</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                            <label >Available:</label>
                            {{ form.available }}
                        </div>
                        <div class="form-group">
                            <label >Stock:</label>
                            {{ form.stock }}
                        </div>
                        <div class="form-group">
                            <label >Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="form-group">
                            <label >Country:</label>
                            {{ form.country }}
                        </div>
                        <input type="hidden" value="{{ ownerID }}" name="productOwnerID" id="id_productOwnerID">
                        <button  type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/updateProduct.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load ratings %}
{% load auth_extras %}
{% block title %}
    Vendor Panel | Update Product
{% endblock %}
{% block content %}
<div id="sidebar" class="span3">
    <div class="box text-center " style="background: #141414">
            <div class="p-a-md">
				    	<p><img src="{% static '/main/img/icons/profile_user.png' %}" class="img-circle w-lg"></p>
				    	<p class="text-lg text-white block">{{ user.username }}</p>
				    	<p class="text-md text-accent">{{ user.level }}</p>
                        {% comment %}<div class="profile-userbuttons">
                            <button type="button" class="btn btn-success btn-sm">Follow</button>
                            <button type="button" class="btn btn-danger btn-sm">Message</button>
                        </div>{% endcomment %}
            </div>
            <div class="row b-t ">
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
					    <a href="{% url 'user_profile' %}">
                                    <i class="fa fa-home"></i>
                                    Overview </a>
                </div>
                {% if request.user|is_vendor %}
                <div class="col-xs-4 m-a-sm text-warn" >
                                <a href="{% url 'user_vendor_listProducts' %}">
                                    <i class="fa fa-user"></i>
                                    Vendor Panel </a>
                </div>
                {% else %}
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/settings/' %} text-warn {% else %} text-side {% endif %}">
                                <a href="{% url 'user_favorites' %}">
                                    <i class="fa fa-thumbs-up"></i>
                                    My Favorites</a>
                </div>
                {% endif %}
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
                                <a href="{% url 'user_order_list' %}">
                                    <i class="fa fa-shopping-cart"></i>
                                    My Orders </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-tasks"></i>
                                    Tasks </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-question"></i>
                                    Help </a>
                </div>
            </div>
        </div>
    <div class="" style="margin-bottom: 20px">
        <p class="side-header"> My Sales</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="{% url 'user_vendor_listProducts' %}" style="color: #6ec2d1">My Products</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_new_order' %}" style="color: #6ec2d1">New Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_ship_order' %}" style="color: #6ec2d1">Shipped Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_complete_order' %}" style="color: #6ec2d1">Completed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_cancel_order' %}" style="color: #6ec2d1">Canceled Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_dispute_order' %}" style="color: #6ec2d1">Disputed Orders</a>
            </li>

        </ul>
    </div>
    {% comment %}<div class="" style="margin-bottom: 20px">
        <p class="side-header"> Products</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="" style="color: #6ec2d1">Add Products</a>
            </li>
        </ul>
    </div>{% endcomment %}

</div>

<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="box" style="background: #141414; color: #666">
                <div class="box-header">
                    <h2 style="color: #6ec2d1">Add Products
                        {% comment %}<a href="{% url '' %}" ><span class="fa fa-plus text-warn m-b-md pull-right" style="font-size: 18px;">Add</span></a>{% endcomment %}
                    </h2>
                </div>
                <div class="box-divider m-0"></div>
                <div class="box-body">
                    <form action="{% url 'user_vendor_updateProduct' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group">
                            <label >Category:</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label >Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label >Slug:</label>
                            {{ form.slug }}
                        </div>
                        <div class="form-group">
                            <label >Description:</label>
                            {{ form.description }}
                        </div>

                        <div class="form-group">
                            <label >Price:</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                            <label >Available:</label>
                            {{ form.available }}
                        </div>
                        <div class="form-group">
                            <label >Stock:</label>
                            {{ form.stock }}
                        </div>
                        <div class="form-group">
                            <label >Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="form-group">
                            <label >Country:</label>
                            {{ form.country }}
                        </div>
                        <input type="hidden" value="{{ ownerID }}" name="productOwnerID" id="id_productOwnerID">
                        <input type="hidden" value="{{ product_id }}" name="productID" id="id_productID">
                        <button  type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}