cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

dark_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView
from accounts import views as account_views
from main import views as main_views
from vendorpanel import views as vendor_views
from main import views as product_views

urlpatterns = [
    path('alibaba/', admin.site.urls),
    path('support/', include('support.urls')),
    # path('vendor/', include('vendor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^signin/$', account_views.LoginView.as_view(), name='signin'),
    url(r'^signin/gpgauth/$', account_views.gpgauth, name='gpgauth'),
    url(r'^signin/gpgverify/$', account_views.gpgverify, name='gpgverify'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/signin')),
    url(r'^profile/usetfalogin', account_views.usetfalogin, name='usetfalogin'),
    #vendor Urls
    url(r'^vendor/addproduct', vendor_views.addProduct, name='user_vendor_addproduct'),
    url(r'^vendor/saveProduct', vendor_views.saveProduct, name='user_vendor_saveProduct'),
    url(r'^vendor/deleteProduct/(?P<product_id>\d+)/$', vendor_views.deleteProduct, name='user_vendor_deleteProduct'),
    url(r'^vendor/editProduct/(?P<product_id>\d+)/$', vendor_views.editProduct, name='user_vendor_editProduct'),
    url(r'^vendor/updateProduct/$', vendor_views.updateProduct, name='user_vendor_updateProduct'),
    url(r'^vendor/listProducts', vendor_views.listProducts, name='user_vendor_listProducts'),
    url(r'^vendorProfile/(?P<id>\d+)/', account_views.vendorProfile, name='vendorProfile'),
    url(r'^vendorPublicProfile/(?P<id>\d+)/', account_views.vendorPublicProfile, name='vendorPublicProfile'),
    url(r'^vendor/newOrders/$', vendor_views.VendorNewOrderListView.as_view(), name='vendor_list_new_order'),
    url(r'^vendor/newOrders/(?P<order_id>\d+)/$', vendor_views.VendorNewOrderDetailView.as_view(), name='vendor_detail_new_order'),
    url(r'^vendor/shipOrders/$', vendor_views.VendorShippedOrderListView.as_view(), name='vendor_list_ship_order'),
    url(r'^vendor/shipOrders/(?P<order_id>\d+)/$', vendor_views.VendorShippedOrderDetailView.as_view(), name='vendor_detail_ship_order'),
    url(r'^vendor/completeOrders/$', vendor_views.VendorCompleteOrderListView.as_view(), name='vendor_list_complete_order'),
    url(r'^vendor/completeOrders/(?P<order_id>\d+)/$', vendor_views.VendorCompleteOrderDetailView.as_view(), name='vendor_detail_complete_order'),
    url(r'^vendor/cancelOrders/$', vendor_views.VendorCancelOrderListView.as_view(), name='vendor_list_cancel_order'),
    url(r'^vendor/cancelOrders/(?P<order_id>\d+)/$', vendor_views.VendorCancelOrderDetailView.as_view(), name='vendor_detail_cancel_order'),
    url(r'^vendor/disputeOrders/$', vendor_views.VendorDisputeOrderListView.as_view(), name='vendor_list_dispute_order'),
    url(r'^vendor/disputeOrders/(?P<order_id>\d+)/$', vendor_views.VendorDisputeOrderDetailView.as_view(), name='vendor_detail_dispute_order'),
    #url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.VendorAcceptOrderView.as_view(), name='vendor_accept_order'),
    url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.accept_order, name='vendor_accept_order'),
    url(r'^vendor/rejectOrder/(?P<order_id>\d+)/$', vendor_views.reject_order, name='vendor_reject_order'),
    url(r'^vendor/newShippingOption/$', vendor_views.addShippingOption, name='vendor_list_new_shipping_option'),
    url(r'^vendor/saveNewShippingOption', vendor_views.saveNewShippingOption, name='user_vendor_saveNewShippingOption'),
    url(r'^vendor/listShippingOptions', vendor_views.listShippingOptions, name='user_vendor_listShippingOptions'),
    url(r'^vendor/editShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.editShippingOption, name='user_vendor_editShippingOption'),
    url(r'^vendor/updateShippingOption/$', vendor_views.updateShippingOption, name='user_vendor_updateShippingOption'),
    url(r'^vendor/deleteShippingOption/(?P<shipping_option_id>\d+)/$', vendor_views.deleteShippingOption, name='user_vendor_deleteShippingOption'),
    #seach url
    url(r'^search/$', product_views.search, name='search'),
    # path('accounts/', include('django.contrib.auth.urls')),

    url(r'^messages/$', product_views.UserMessageListView.as_view(), name='message_list'),

    #inbox url
    url(r'^inbox/$', product_views.UserInboxListView.as_view(), name='inbox_list'),
    url(r'^inbox/(?P<message_id>\d+)/delete/$', product_views.deleteMessage, name='inbox_delete_message'),
    url(r'^inbox/send/$', product_views.inbox_send, name='inbox_send'),
    url(r'^inbox/send/(?P<receiver_id>\d+)/$', product_views.inbox_send, name='inbox_send'),

    path('account/', include('accounts.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),  # Redirects url "/accounts" to "/account"
    # url(r'^accounts/', include("accounts.passwords.urls")),

    # path('accounts/', include("accounts.passwords.urls")),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main.urls')),
    #star Rating Url
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as views
from main import views as main_views
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    #url(r'^messages/', views.UserMessageListView.as_view(), name='message_list'),

]

support/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'support'

urlpatterns =[

    url('^$', views.support_list, name='support_list'),
    url('^customer_chat/$', views.customer_support, name='customer_support'),
    url('^customer_ticket_list/$', views.customer_ticket_list, name='customer_ticket_list'),
    url(r'^customer_ticket/(?P<c_id>\d+)', views.customer_ticket, name='customer_ticket'),
    url('^create_ticket/$', views.create_ticket, name='create_ticket'),
    url('^customer_post_message/$', views.customer_post_message, name='customer_post_message'),
    url('^customer_post_ticket/$', views.customer_post_ticket, name='customer_post_ticket'),
    url('^customer_ticket_replay/$', views.customer_ticket_replay, name='customer_ticket_replay'),
    url(r'^ticket_state_change/(?P<state>\d+)/(?P<ticket_id>\d+)', views.ticket_state_change, name='ticket_state_change'),

    url('^admin_support/$', views.admin_support, name='admin_support'),
    url('^(?P<user>[-\w]+)/$', views.admin_support_user, name='admin_support_user'),
    url('^(?P<user>[-\w]+)/admin_post_message/$', views.admin_post_message, name='admin_post_message'),

]

main/views.py
from cart.forms import CartAddProductForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, ListView
from orders.models import OrderItem, Order
from django.shortcuts import render, get_object_or_404, redirect
from cryptowatch_client import Client

from .models import Category, Product, Message, BTCPrice
from django_countries import countries
from accounts.models import User, VendorTerm
from django.db.models import Q
from star_ratings.models import Rating, UserRating
from accounts.forms import LoginForm
from django.db.models import Q
from vendorpanel.models import ShippingOption

# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             msg = "Hello " + user.username + ". Welcome to OnionShop."
#             messages.success(request, msg)
#             return redirect("product_list")
#     else:
#         form = SignUpForm()
#     return render(request, 'registration/signup.html', {'form': form})
#
#
# def signin(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             msg = "Welcome back" + user.username
#             messages.success(request, msg)
#             return redirect("product_list")
#     else:
#         form = LoginForm(request)
#     return render(request, 'registration/login.html', {'form': form})
def cryptocurrencies():
    btcPrice = BTCPrice.objects.all().order_by('-id').first()
    if btcPrice == None:
        cryptoPrice={"btcusd":"",'btcgbp':"",'btceur':""}
    else:
        cryptoPrice={"btcusd":btcPrice.btcusd,'btcgbp':btcPrice.btcgbp,'btceur':btcPrice.btceur}
    return cryptoPrice

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    message = len(Message.objects.filter(check=False))
    #message = len(Message.objects.all())
    form = LoginForm
    if category_slug:
        print(category_slug)
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    #cryptocurrenies Data
    cryptoData=cryptocurrencies()

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'cryptoData': cryptoData,
        'countries': countries,
        'form': form,
        'new_message': message,
    }
    return render(request, 'main/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    product_stock = cart_product_form.get_product_stock(id)
    categories = Category.objects.all()
    cryptoData = cryptocurrencies()
    message = len(Message.objects.filter(check=False))

    productVendor = Product.objects.values('productOwnerID', 'country').get(id=id)
    country = countries.name(productVendor.get('country'))
    productVendor = productVendor.get('productOwnerID')

    vendor = User.objects.values('id', 'username').filter(id=productVendor, is_vendor=True)
    ratings = Rating.objects.filter(object_id=id)
    term_conditions = VendorTerm.objects.filter(userId=productVendor)
    if ratings:
        ratingsObject = UserRating.objects.filter(rating=ratings.first().id).first()
    else:
        ratingsObject = None
    if request.user.is_authenticated and product.country==request.user.country:
        shipping_options = ShippingOption.objects.filter(
                           shipping_area='domestic',
                           vendor=product.productOwnerID)
    else:
        shipping_options = ShippingOption.objects.filter(
                           shipping_area='international',
                           vendor=product.productOwnerID)

    context = {
        'product': product,
        'categories': categories,
        'cart_product_form': cart_product_form,
        'product_stock': product_stock,
        'vendor': vendor[0],
        'country': country,
        'ratingsObject': ratingsObject,
        'cryptoData': cryptoData,
        'new_message': message,
        'term_conditions': term_conditions[0],
        'shipping_options': shipping_options
    }
    return render(request, 'main/product/detail.html', context)


def search(request):
    if request.method == 'GET':
        message = len(Message.objects.filter(check=False))
        price = 0
        if request.GET.get('price'):
            price = int(request.GET.get('price'))

        country = request.GET.get('country', None)
        category = request.GET.get('category', None)
        categoryID = Category.objects.filter(name=category)
        products = {}

        if price > 0 and category is '' and country is '':
            products = Product.objects.filter(Q(price__gte=price))
        elif category and price is 0 and country is '':
            print("===================================")
            products = Product.objects.filter(category__in=categoryID)
        elif country and price is 0 and category is '':
            products = Product.objects.filter(country=country)
        elif price > 0 and category and country is '':
            products = Product.objects.filter(Q(price__gte=price), category__in=categoryID)
        elif country and price > 0 and category is '':
            products = Product.objects.filter(Q(price__gte=price), country=country)
        elif country and category and price is 0:
            products = Product.objects.filter(country=country, category__in=categoryID)
        elif price > 0 and category and country:
            products = Product.objects.filter(Q(price__gte=price), category__in=categoryID, country=country)
        elif price is 0 and category is '' and country is '':
            products = Product.objects.all

        categories = Category.objects.all()
        # cryptocurrenies Data
        cryptoData = cryptocurrencies()

        context = {
            'category': category,
            'categories': categories,
            'products': products,
            'cryptoData': cryptoData,
            'countries': countries,
            'new_message': message

        }
    else:
        raise  Exception("405")
    return render(request, 'main/product/list.html', context)


# User Notification page
class UserMessageListView(LoginRequiredMixin, ListView):
    template_name = 'message/message_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        admin_ids = User.objects.filter(id=True)
        return Message.objects.filter(Q(sender__in=admin_ids) & Q(receiver=self.request.user)).order_by('-created_at')
               #| Message.objects.filter(sender=self.request.user)


# User Inbox page
class UserInboxListView(LoginRequiredMixin, ListView):
    template_name = 'inbox/inbox_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        return Message.objects.filter((Q(sender=self.request.user) & Q(sender_removed=False)) |
                                      (Q(receiver=self.request.user) & Q(receiver_removed=False))).order_by('-created_at')
               #| Message.objects.filter(sender=self.request.user)


# User Inbox Send page
def inbox_send(request, receiver_id = '0'):
    if request.method == 'POST':
        obj = Message()
        obj.sender_id = request.user.id
        obj.receiver_id = request.POST.get('receiver_id')
        obj.content = request.POST.get('content')
        obj.save()

        msg = "Message sent successfully"
        messages.success(request, msg)
        return redirect("inbox_send")
    else:
        users = User.objects.all
        context_object = {'users': users, 'receiver_id': int(receiver_id)}
    return render(request, 'inbox/inbox_send.html', context_object)


# User Inbox Delete Message
def deleteMessage(request, message_id=''):
    message = Message.objects.get(pk=message_id)
    message_object = Message.objects.filter(id=message_id)

    if message.sender_id == request.user.id:
        message_object.update(sender_removed=True)
    elif message.receiver_id == request.user.id:
        message_object.update(receiver_removed=True)

    msg = "Message is deleted"
    messages.success(request, msg)
    return redirect("inbox_list")

# def user_profile(request):
#     if request.user.is_authenticated:
#         context = {
#             'object': request.user,
#         }
#         return render(request, 'main/profile/user-profile.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#
#
# class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
#     form_class = UserProfileChangeForm
#
#     def get_object(self, queryset=None):
#         return self.request.user
#
#     def get_success_url(self):
#         return redirect("user_profile")
#
#
# def profile_orders(request):
#     if request.user.is_authenticated is True:
#         orders = Order.objects.filter(user=request.user)
#         context = {
#             'orders': orders,
#         }
#         return render(request, 'main/profile/order-list.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#
#
# def profile_order(request, order_id):
#     if request.user.is_authenticated is True:
#         orders = OrderItem.objects.filter(order_id=order_id, author=request.user)
#
#         context = {
#             'orders': orders,
#         }
#         return render(request, 'main/profile/order-detail.html', context)
#     else:
#         return render(request, 'main/nlogin.html')
#

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap styles -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet"/>
    <!-- Customize styles -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
    <!-- font awesome styles -->
	<link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/app.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/star-ratings.css' %}" rel="stylesheet">
    {% comment %}<link rel="stylesheet" href="{% static 'assets/css/material-design-icons.css' %}" type="text/css">{% endcomment %}
		<!--[if IE 7]>
			<link href="css/font-awesome-ie7.min.css" rel="stylesheet">
		<![endif]-->

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

	<!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.ico' %}">
	<script type="text/javascript" src="{% static 'main/js/star-ratings.min.js' %}"></script>
    {% block extra_head %}

    {% endblock %}

</head>
<body>

{#Navbar#}
{% include 'main/navbar.html' %}

{#Django messages#}


<div class="container">
	<div id="gototop"> </div>
	<header id="header" >
	</header>

{% if messages %}
	{% for message in messages %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert success alert-dismissable" style="border: none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{message}}
            </div>
			{% comment %}<div class="container alert success messages mt-5" style="border: none">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>{% endcomment %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
			<div class="alert info alert-dismissable" style="border: none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{message}}
            </div>
            {% comment %}<div class="container alert info messages mt-5" style="border: none">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>{% endcomment %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert warning alert-dismissable" style="border: none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{message}}
            </div>
			{% comment %}<div class="container alert warning messages mt-5" style="border: none">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>{% endcomment %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert error alert-dismissable" style="border: none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{message}}
            </div>
			{% comment %}<div class="container alert danger messages mt-5" style="border: none">
				<span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				{% if 'safe' in message.tags %}
				{{ message|safe }}<br/>
				{% else %}
				{{ message }}<br/>
				{% endif %}
				</span>
			</div>{% endcomment %}
		{% endif %}
	{% endfor %}
{% endif %}

	<div class="row">
		{% block content %}
		{% endblock %}

	</div>

</div>



 <!--Placed at the end of the document so the pages load faster-->
    <script src="{% static 'assets/js/jquery.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollTo-1.4.3.1-min.js' %}"></script>
    <script src="{% static 'assets/js/shop.js' %}"></script>

</body>
</html>

main/templates/main/navbar.html
{% load static %}
{% load widget_tweaks %}

<!--<nav class="d-lg-none" style="padding:50px">
    <input class="burger-check" id="burger-check" type="checkbox"><label for="burger-check" class="burger"></label>
    <div id="navigation1" class="navigation">
      <ul>
        <li {% if not category %} class="active"{% endif %}><a href="{% url 'product_list' %}">All</a></li>
      </ul>
      {% for c in categories %}
          <li {% if category.slug == c.slug %} class="active"{% endif %}>
              <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          </li>
      {% endfor %}
    </div>
</nav>-->

<div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #0c0c0c">
	<div class="topNav" style="background-color: #0c0c0c">
		<div class="container" style="height: 5rem">
			<div class="alignR" style="height: 5rem">
				<div class="pull-left span4">
					<!--<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-facebook"></span></a>
					<a href="#"><span class="icon-youtube"></span></a>
					<a href="#"><span class="icon-tumblr"></span></a>-->
					<h3 style="display:none;">
						<a class="logo" href="{% url 'product_list' %}">
							<img src="{% static 'assets/img/logo-bootstrap-shoping-cart.png' %}" >
						</a>
					</h3>
				</div>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'inbox_list' %}"><p class="header"><span class="fa fa-envelope"></span> Messages</p></a>
                    <a href="{% url 'user_profile' %}"><p class="header"><span class="icon-user"></span> Profile</p></a>
                    <a href="{% url 'logout' %}"><p class="header"><span class="fa fa-sign-out"></span> LogOut</p></a>
                    <a href="{% url 'message_list' %}"><p class="header"><span class="fa fa-bell"></span> Notification</p></a>
                {% else %}
                    <a href="{% url 'signin' %}"><p class="header"><span class="fa fa-sign-in"></span> Sign-in</p></a>
                    <a href="{% url 'signup' %}"><p class="header"><span class="fa fa-sign-out"></span> Sign-up</p></a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <a href="{% url 'support:admin_support' %}"><p class="header"><span class="icon-support"></span> Admin Support</p></a>
                    {% else %}
                        <a href="{% url 'support:support_list' %}"><p class="header"><span class="fa fa-question"></span> Support</p></a>
                    {% endif %}
                {% endif %}
                <a href="{% url 'cart:cart_detail' %}" style="margin-right:20px">
                    <p class="header">
                        <span class="icon-shopping-cart"></span>
                        {% with totail_items=cart|length %}
                            {% if cart|length > 0 %}
                                {{ totail_items }}
                            {% else %}
                                0
                            {% endif %}
                        {% endwith %}Item(s)
                    </p>
                </a>
				<!--<a href="index.html"><h3><span class="icon-home"></span> Home</h3></a>
				<a href="#"><span class="icon-user"></span> My Account</a>
				<a href="register.html"><span class="icon-edit"></span> Free Register </a>
				<a href="contact.html"><span class="icon-envelope"></span> Contact us</a>
				<a href="cart.html"><span class="icon-shopping-cart"></span> 2 Item(s) - <span class="badge badge-warning"> $448.42</span></a>-->
			</div>
		</div>
	</div>
</div>

<!--<div id="signin" class="modal fade" role="dialog">
    <div class="modal-dialog">

    &lt;!&ndash; Modal content&ndash;&gt;
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Login</h4>
            </div>
            <div class="modal-body">

                <form action="{% url 'signin' %}" method="post" style="margin:auto;margin-top:6%;width:40%;">{% csrf_token %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                            <div class="invalid-feedback">
                            {{ error }}
                            </div>
                            {% endfor %}
                        {% else %}
                            {% render_field field class="form-control is-valid" %}
                        {% endif %}
                    {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}
                    </div>
                 {% endfor %}

                    <br>
                    <input type="submit" class="btn btn-primary" value="Login" style="margin:auto">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>-->

main/templates/main/nlogin.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 12%">
            <div class="col-md-8 col-md-offset-2">
                <p><strong>you need to be logged in to access this page</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/nsuper.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 12%">
            <div class="col-md-8 col-md-offset-2">
                <p><strong>you need to be the superuser to access this page</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}